import json
import datetime
import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

class DillyReportGenerator:
    def __init__(self, audit_data):
        self.data = audit_data
        self.filename = f"dilly_report_{self.data['candidate']}.pdf"

    def generate(self):
        doc = SimpleDocTemplate(self.filename, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Header
        title = Paragraph(f"<font size=24 color='#2E5BFF'>DILLY AUDIT REPORT</font>", styles['Title'])
        story.append(title)
        story.append(Spacer(1, 12))

        # Candidate Info
        story.append(Paragraph(f"<b>Candidate:</b> {self.data['candidate']}", styles['Normal']))
        story.append(Paragraph(f"<b>Date:</b> {self.data['timestamp']}", styles['Normal']))
        story.append(Paragraph(f"<b>Status:</b> <font color={'green' if self.data['veracity_status'] == 'VERIFIED' else 'red'}>{self.data['veracity_status']}</font>", styles['Normal']))
        story.append(Spacer(1, 24))

        # Score Section
        score_val = self.data['dilly_grit_score']
        score_color = 'green' if score_val > 70 else 'orange' if score_val > 40 else 'red'
        story.append(Paragraph(f"<font size=18>Dilly Grit Score: <font color='{score_color}'>{score_val}/100</font></font>", styles['Heading2']))
        story.append(Spacer(1, 12))

        # Metadata Table
        meta_data = [["Metric", "Value"]]
        for k, v in self.data['metadata'].items():
            meta_data.append([k.replace('_', ' ').title(), str(v)])
        
        t = Table(meta_data, colWidths=[200, 200])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        story.append(t)
        story.append(Spacer(1, 24))

        # Footer
        footer_text = "<i>This report was generated by the Dilly Engine. Veracity is determined by cross-referencing resume claims against live repository activity and commit velocity.</i>"
        story.append(Paragraph(footer_text, styles['Italic']))

        doc.build(story)
        print(f"Report generated: {self.filename}")
        return self.filename

# Update the auditor to include the report generation
import requests

class DillyGitHubAuditor:
    def __init__(self, username):
        self.username = username
        self.base_url = "https://api.github.com"
        self.token = os.getenv("GITHUB_TOKEN") 
        self.headers = {"Authorization": f"token {self.token}"} if self.token else {}

    def fetch_user_data(self):
        response = requests.get(f"{self.base_url}/users/{self.username}", headers=self.headers)
        return response.json() if response.status_code == 200 else None

    def fetch_repos(self):
        response = requests.get(f"{self.base_url}/users/{self.username}/repos?sort=updated&per_page=100", headers=self.headers)
        return response.json() if response.status_code == 200 else []

    def calculate_grit_score(self, user_data, repos):
        if not user_data: return 0
        total_repos = user_data.get('public_repos', 0)
        if total_repos == 0: return 0
        now = datetime.datetime.now()
        active_repos = sum(1 for r in repos if (now - datetime.datetime.strptime(r['updated_at'], "%Y-%m-%dT%H:%M:%SZ")).days < 30)
        velocity = (active_repos / total_repos) * 100
        score = (total_repos * 2) + (velocity * 0.8)
        return min(round(score, 2), 100)

    def run_audit(self):
        user = self.fetch_user_data()
        repos = self.fetch_repos()
        score = self.calculate_grit_score(user, repos)
        
        report_data = {
            "candidate": self.username,
            "dilly_grit_score": score,
            "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "veracity_status": "VERIFIED" if score > 50 else "PENDING",
            "metadata": {
                "public_repos": user.get('public_repos', 0) if user else 0,
                "active_projects_30d": sum(1 for r in repos if (datetime.datetime.now() - datetime.datetime.strptime(r['updated_at'], "%Y-%m-%dT%H:%M:%SZ")).days < 30),
                "account_age_days": (datetime.datetime.now() - datetime.datetime.strptime(user['created_at'], "%Y-%m-%dT%H:%M:%SZ")).days if user else 0
            }
        }
        
        gen = DillyReportGenerator(report_data)
        gen.generate()
        return report_data

if __name__ == "__main__":
    import sys
    name = sys.argv[1] if len(sys.argv) > 1 else "Dilan1234321"
    auditor = DillyGitHubAuditor(name)
    print(json.dumps(auditor.run_audit(), indent=4))
