export const ALL_COHORTS = [
  'Software Engineering & CS',
  'Data Science & Analytics',
  'Cybersecurity & IT',
  'Finance & Accounting',
  'Marketing & Advertising',
  'Consulting & Strategy',
  'Management & Operations',
  'Economics & Public Policy',
  'Entrepreneurship & Innovation',
  'Healthcare & Clinical',
  'Life Sciences & Research',
  'Physical Sciences & Math',
  'Social Sciences & Nonprofit',
  'Media & Communications',
  'Design & Creative',
  'Legal & Compliance',
  'Human Resources & People',
  'Supply Chain & Logistics',
  'Education & Teaching',
  'Real Estate & Construction',
  'Environmental & Sustainability',
  'Hospitality & Events',
];

export const COHORT_COLORS: Record<string, string> = {
  'Software Engineering & CS':   '#2B3A8E',
  'Data Science & Analytics':    '#7C3AED',
  'Cybersecurity & IT':          '#0F766E',
  'Finance & Accounting':        '#2B3A8E',
  'Marketing & Advertising':     '#DB2777',
  'Consulting & Strategy':       '#7C3AED',
  'Management & Operations':     '#0369A1',
  'Economics & Public Policy':   '#1D4ED8',
  'Entrepreneurship & Innovation': '#EA580C',
  'Healthcare & Clinical':       '#0284C7',
  'Life Sciences & Research':    '#16A34A',
  'Physical Sciences & Math':    '#0F766E',
  'Social Sciences & Nonprofit': '#7C3AED',
  'Media & Communications':      '#DB2777',
  'Design & Creative':           '#E11D48',
  'Legal & Compliance':          '#1E3A8A',
  'Human Resources & People':    '#0369A1',
  'Supply Chain & Logistics':    '#B45309',
  'Education & Teaching':        '#16A34A',
  'Real Estate & Construction':  '#B45309',
  'Environmental & Sustainability': '#16A34A',
  'Hospitality & Events':        '#EA580C',
  General:                       '#2B3A8E',
};

export function getCohortColor(cohort: string): string {
  return COHORT_COLORS[cohort] ?? '#2B3A8E';
}
