// UTampa approved majors list
export const APPROVED_MAJORS = [
  'Accounting',
  'Advertising and Public Relations',
  'Allied Health',
  'Biochemistry',
  'Biology',
  'Business Administration',
  'Chemistry',
  'Communication',
  'Computer Information Systems',
  'Computer Science',
  'Criminal Justice',
  'Cybersecurity',
  'Data Science',
  'Digital Arts and Design',
  'Economics',
  'Education',
  'English',
  'Environmental Science',
  'Exercise Science',
  'Finance',
  'Forensic Science',
  'Government and World Affairs',
  'Health Sciences',
  'History',
  'Information Technology',
  'International Business',
  'Journalism',
  'Kinesiology',
  'Liberal Arts',
  'Management',
  'Marine Science',
  'Marketing',
  'Mathematics',
  'Music',
  'Nursing',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Sport Management',
  'Statistics',
  'Theatre Arts',
];
