"""
Candidate company slugs for ATS discovery.

A big list of potential Greenhouse / Lever / Ashby slugs to probe.
Most will 404 — that's expected. The discovery pass hits each against
the vendor's public API; successful hits get persisted into
`discovered_boards` for the main crawler to pick up on every run.

Sources:
  - Y Combinator public company directory (top ~2,000 W23-F25 cos)
  - Known tech unicorns + Series B+ from public news
  - Fortune 1000 + adjacent enterprise
  - Climate tech / biotech / fintech curated sets

This file intentionally contains more candidates than will succeed —
wider net means more discovered boards. Dedup is handled at probe time.

Format: lowercase, hyphen-separated, no whitespace. The same name may
appear multiple times in different format variants (e.g. 'stripe-inc'
+ 'stripe') since different companies use different conventions.
"""

# Curated as lowercase a-z0-9- slugs. We try the exact slug as-is
# against each vendor's public board API. Most 404; successful ones
# get persisted.
CANDIDATE_SLUGS: list[str] = [
    # ── AI / ML / LLMs ──────────────────────────────────────────
    "anthropic", "openai", "xai", "cohere", "mistral", "mistralai", "ai21labs",
    "inflection", "adept", "character-ai", "characterai", "replicate",
    "huggingface", "stability", "stabilityai", "runwayml", "midjourney",
    "pika-labs", "pikalabs", "elevenlabs", "eleven", "suno", "udio",
    "perplexity", "glean", "harvey", "harvey-ai", "hebbia", "magic",
    "magic-dev", "sierra", "sierra-ai", "decagon", "decagon-ai",
    "together-ai", "togetherxyz", "fireworks", "fireworks-ai",
    "replicate-com", "modal", "modal-labs", "baseten", "lamini",
    "groq", "cerebras", "tenstorrent", "sambanova", "rain",
    "rain-ai", "lightmatter", "luminous-ai", "psiquantum", "quantinuum",
    "ionq", "rigetti", "atom-computing", "quera", "pasqal",
    "ambient", "ambient-ai", "cresta", "observe-ai", "regal",
    "regal-ai", "augment", "imbue", "reka", "reka-ai",
    "poolside", "cognition", "devin", "cursor", "cursor-so",
    "bolt-new", "lovable", "vercel-v0", "codeium", "supermaven",
    "warp", "warpdotdev", "zed", "zed-industries", "fig-io",
    "raycast", "raycast-app", "arc-browser", "the-browser-company",
    "thebrowsercompany", "continuedev", "aider-ai", "sweep-dev",
    "langchain", "langchain-ai", "llamaindex", "langfuse", "braintrust",
    "weights-and-biases", "wandb", "comet-ml", "labelbox", "scale",
    "scaleai", "snorkel", "snorkel-ai", "arize", "arize-ai", "truera",
    "gantry", "fiddler-ai", "whylabs", "galileo-ai", "humanloop",
    "promptlayer", "pinecone", "weaviate", "qdrant", "chroma",
    "trychroma", "milvus", "vectara", "marqo", "lancedb",
    "convex", "convex-dev", "temporal", "temporal-tech",

    # ── Dev tooling / infra ─────────────────────────────────────
    "netlify", "vercel", "render", "fly-io", "fly", "railway", "railway-app",
    "cloudflare", "fastly", "bunny-net", "cdn77", "akamai",
    "aws", "gcp", "azure",
    "supabase", "firebase", "planetscale", "neon", "neondatabase", "xata",
    "cockroachdb", "cockroach-labs", "scylla", "scylladb", "yugabyte",
    "materialize", "rockset", "singlestore", "imply", "tinybird",
    "redpanda", "confluent", "kafka", "aiven", "snowflake",
    "databricks", "motherduck", "firebolt", "starburst", "dremio",
    "datacoral", "trino", "presto", "clickhouse",
    "grafana", "grafana-labs", "prometheus", "prometheus-io",
    "datadoghq", "datadog", "splunk", "newrelic", "dynatrace",
    "appdynamics", "sumologic", "sumo-logic", "honeycomb", "lightstep",
    "chronosphere", "cribl", "observe", "observe-inc", "lumigo",
    "sentry", "sentry-io", "rollbar", "bugsnag", "loggly",
    "statuspage", "better-stack", "betteruptime", "pingdom", "uptimerobot",
    "opsgenie", "pagerduty", "incident-io", "incident", "firehydrant",
    "rootly", "blameless", "blameless-io", "courier", "twilio",
    "plivo", "vonage", "bandwidth", "messagebird", "sinch",
    "sendgrid", "mailgun", "postmark", "resend", "loops",
    "customer-io", "customerio", "braze", "iterable", "klaviyo",
    "mailchimp", "activecampaign", "drip", "omnisend", "postscript",
    "attentive", "attentive-inc", "klaviyo-inc",
    "algolia", "meilisearch", "typesense", "elastic", "elasticsearch",
    "mongodb", "mongodb-inc", "redis", "redis-io", "memcached",
    "couchbase", "arangodb", "dgraph", "neo4j", "surrealdb",
    "edgedb", "prisma", "prismaio",
    "docker", "docker-inc", "kubernetes", "canonical", "redhat",
    "suse", "tanzu",
    "hashicorp", "terraform", "ansible", "pulumi", "chef",
    "puppet", "spacelift", "env0", "scalr", "terraform-cloud",
    "github", "gitlab", "bitbucket", "sourcehut",
    "jira", "atlassian", "linear", "linear-app", "height", "shortcut",
    "clickup", "monday", "asana", "notion", "airtable",
    "tana", "capacities", "obsidian", "roam", "logseq",
    "circleci", "buildkite", "codefresh", "semaphore", "drone",
    "harness", "harness-io", "jenkins", "teamcity",
    "launchdarkly", "statsig", "growthbook", "flagsmith", "devcycle",
    "split-software", "optimizely", "amplitude", "mixpanel",
    "heap", "posthog", "pendo", "fullstory", "hotjar",
    "rudderstack", "segment", "segment-io", "mparticle", "hightouch",
    "census",

    # ── Fintech ──────────────────────────────────────────────────
    "stripe", "square", "block", "shopify", "plaid",
    "paddle", "lemon-squeezy", "revenuecat", "recharge", "rechargepayments",
    "adyen", "checkout", "checkoutcom", "rapyd", "nium",
    "airwallex", "brex", "ramp", "mercury", "novo", "novofund",
    "chime", "sofi", "varo", "current", "step",
    "dave", "cashapp", "venmo", "zelle",
    "robinhood", "public", "webull", "moomoo", "tastyworks",
    "alpaca", "alpaca-markets", "tradier", "questrade",
    "wealthfront", "betterment", "ellevest", "personalcapital",
    "plaid-inc", "finix", "finix-payments", "modern-treasury",
    "unit", "unit21", "column", "column-tax", "treasury-prime",
    "highnote", "lithic", "marqeta", "bond", "synapse",
    "galileo-ft", "ncino", "nCino", "affirm", "klarna", "afterpay",
    "sezzle", "paypal", "stripe-atlas", "mercury-bank",
    "deel", "remote-com", "oyster", "velocity-global", "omnipresent",
    "rippling", "gusto", "justworks", "trinet", "paychex",
    "carta", "pulley", "angellist-venture", "republic",
    "forge-global", "equityzen", "ourcrowd",
    "nerdwallet", "creditkarma", "lendingtree", "sofi-inc",
    "truework", "argyle", "atomic", "atomicfi",

    # ── Consumer / e-commerce / DTC ─────────────────────────────
    "airbnb", "doordash", "instacart", "uber", "lyft", "grubhub", "postmates",
    "gopuff", "goPuff", "chowbus", "wonder", "wondershake",
    "deliveroo", "just-eat", "swiggy", "zomato",
    "opendoor", "zillow", "redfin", "compass", "better-com",
    "offerpad", "homelight",
    "faire", "faire-wholesale", "thrasio", "perch",
    "rec-room", "roblox", "epic-games", "riot", "unity", "unity3d",
    "chainguard", "anchore", "sysdig", "aquasec", "snyk",
    "wiz-io", "orca-security", "lacework", "bridgecrew",
    # DTC
    "warby-parker", "allbirds", "bombas", "rothys", "glossier",
    "casper", "purple", "leesa", "saatva", "nectar-sleep",
    "harrys", "dollar-shave-club", "billie", "hims", "hers",
    "roman-rory", "ro-co", "forhims", "forhers",
    "stitch-fix", "rent-the-runway", "thredup", "poshmark", "depop",
    "goat", "stockx", "grailed", "the-realreal", "vestiaire",
    "peloton", "tonal", "hydrow", "tempo", "mirror",
    "oura", "ourahealth", "whoop", "fitbit", "garmin",
    "headspace", "calm", "better-help", "talkspace", "cerebral",
    "noom", "weightwatchers", "futurefit", "future-app",
    # Media + social
    "spotify", "pandora", "tidal", "soundcloud",
    "netflix", "hulu", "disney", "disneycareers",
    "discord", "slack", "slack-tech", "telegram", "signal-app",
    "pinterest", "reddit", "twitter", "x-company", "threads-app",
    "substack", "medium", "ghost", "beehiiv", "convertkit",
    "patreon", "onlyfans", "buymeacoffee",

    # ── Healthcare / biotech ────────────────────────────────────
    "flatiron", "flatiron-health", "tempus", "tempus-labs", "tempusai",
    "guardant-health", "grail", "exact-sciences", "myriad-genetics",
    "10x-genomics", "illumina", "twist-bioscience", "ginkgo",
    "ginkgo-bioworks", "zymergen", "berkeley-lights", "nautilus",
    "singular-genomics", "pacific-biosciences", "oxford-nanopore",
    "absci", "relay-therapeutics", "vertex", "vertex-pharmaceuticals",
    "biogen", "moderna", "biontech", "regeneron", "alnylam",
    "bluebird-bio", "crispr-therapeutics", "editas", "intellia",
    "sana-biotech", "beam-therapeutics", "verve-therapeutics",
    "pathai", "paige-ai", "recursion", "insitro", "schrodinger",
    "schrödinger", "atomwise", "benevolentai", "exscientia",
    "isomorphic-labs", "isomorphic", "generate-biomedicines",
    "terray-therapeutics",
    "oscar-health", "oscar", "bright-health", "alignment-healthcare",
    "devoted-health", "clover-health", "cityblock-health",
    "one-medical", "onemedical", "forward-health", "forward",
    "carbon-health", "firefly-health", "fireflyhealth", "ro-health",
    "talkspace-inc", "lyra-health", "spring-health", "modern-health",
    "omada-health", "teladoc", "amwell", "mdlive",
    "zocdoc", "solv-health", "zocdoc-careers",
    "olive", "olive-ai", "augmedix", "notable-health",
    "maven-clinic", "kindbody", "cofertility", "carrot-fertility",
    "progyny",

    # ── Climate / energy / mobility ─────────────────────────────
    "tesla", "rivian", "lucidmotors", "lucid-motors", "polestar",
    "nio", "xpeng", "li-auto",
    "waymo", "cruise", "zoox", "aurora", "motional", "nuro",
    "argo-ai", "embark", "embark-trucks", "kodiak-robotics",
    "torc-robotics", "aurora-innovation", "applied-intuition",
    "redwood-materials", "form-energy", "commonwealth-fusion",
    "helion-energy", "helion", "tae-technologies",
    "fusion-industry", "quaise",
    "climeworks", "carbon-engineering", "charm-industrial",
    "running-tide", "ebb-carbon", "heirloom-carbon",
    "pachama", "sylvera", "patch-io", "watershed", "watershed-tech",
    "persefoni", "normative", "normative-io", "sweep-earth",
    "palmetto", "palmetto-com", "sunrun", "sunnova", "sunpower",
    "tesla-energy",
    "northvolt", "quantum-scape", "solid-power", "sila-nanotech",
    "relativity-space", "spacex", "blue-origin", "planet-labs",
    "astranis", "varda", "varda-space", "vast-space", "stoke-space",
    "impulse-space", "firefly-aerospace", "rocket-lab",

    # ── Security ────────────────────────────────────────────────
    "okta", "auth0", "clerk", "clerk-inc", "workos", "workos-inc",
    "descope", "stytch", "frontegg",
    "1password", "bitwarden", "dashlane", "keepersecurity", "lastpass",
    "duo-security", "duosecurity", "cisco-duo", "yubico", "trezor",
    "tanium", "crowdstrike", "sentinelone", "carbon-black",
    "cybereason", "cylance", "cynet",
    "palo-alto-networks", "paloalto", "fortinet", "checkpoint",
    "zscaler", "netskope", "menlo-security", "island",
    "lookout", "mobile-iron", "jamf", "kandji", "addigy",
    "beyond-trust", "beyondtrust", "cyberark", "delinea",
    "snyk-io", "checkmarx", "veracode", "semgrep", "socket",
    "chainguard-dev", "anchore-io", "aquasecurity",
    "huntress", "huntresslabs", "red-canary", "arctic-wolf",
    "dragos", "claroty", "nozomi-networks",

    # ── Enterprise SaaS / productivity ──────────────────────────
    "workday", "workiva", "anaplan", "blackline", "coupa",
    "freshworks", "freshworks-inc", "zendesk", "helpscout", "intercom",
    "frontapp", "front", "gorgias", "hiver", "missive",
    "calendly", "doodle", "hubspot-calendar", "savvycal",
    "docusign", "dropbox-sign", "hellosign", "adobe-sign", "pandadoc",
    "notion-inc", "coda-io", "craft-docs", "bear-app", "ulysses",
    "miro-inc", "mural", "figjam", "whimsical", "creately",
    "framer", "webflow", "squarespace", "wix", "shopify-inc",
    "contentful", "sanity-io", "sanityio", "strapi", "storyblok",
    "prismic", "hygraph", "payload-cms", "payloadcms",
    "loom", "vidyard", "wistia", "brightcove", "mux",
    "superhuman", "hey-com", "front-inc", "spike-email",
    "clickup-inc", "clickup-app",

    # ── Logistics / operations ──────────────────────────────────
    "flexport", "shippo", "easypost", "shipbob", "shipmonk",
    "convoy", "convoy-inc", "loadsmart", "uber-freight",
    "trackman", "project44", "fourkites",
    "samsara", "samsara-inc", "motive", "motive-com", "keeptruckin",
    "zipline", "skydio", "wingcopter", "matternet",
    "shield-ai", "anduril", "anduril-industries", "saronic",
    "epirus",

    # ── Consulting / services / legal ───────────────────────────
    "mckinsey", "bain", "boston-consulting-group", "bcg",
    "deloitte", "ey", "pwc", "kpmg", "accenture",
    "capgemini", "genpact", "infosys", "wipro", "tata-consultancy",
    "oliver-wyman", "kearney", "lek-consulting", "adlittle",
    "zs-associates", "alvarez-marsal", "fti-consulting",
    "guidepoint", "alphasights", "third-bridge", "glg",
    "clio", "clio-legal", "everlaw", "relativity", "logikcull",
    "lexisnexis", "thomson-reuters", "bloomberg-law",

    # ── Education / edtech ──────────────────────────────────────
    "duolingo", "coursera", "udemy", "skillshare", "masterclass",
    "chegg", "quizlet", "brainly", "socratic",
    "khan-academy", "khanacademy", "outschool", "codecademy",
    "brilliant", "brilliant-org", "outlier-org",
    "turing", "turingcom", "lambda-school", "bloomtech",
    "andela", "toptal-team",
    "nearpod", "clever-inc", "powerschool", "blackboard",
    "canvas-inst", "instructure",
    "prodigy-math", "epic-reading", "ixl-learning", "renaissance",

    # ── Misc high-signal ────────────────────────────────────────
    "handshake", "wellfound", "welcomeplatform", "lever-co",
    "greenhouse-software", "ashby-hq", "ashbyhq",
    "workable", "workableinc",
    "betterup", "sanebox", "airkit", "superhuman-mail",

    # ──────────────────────────────────────────────────────────────
    # ── COHORT EXPANSION (build 437+) ─────────────────────────────
    # Wide-net additions across non-tech cohorts so the discovery
    # probe lands boards in finance, healthcare, retail, education,
    # consulting, government, media, energy, manufacturing, and more.
    # Most will 404; the live ones each contribute 50-500 jobs to
    # the feed.
    # ──────────────────────────────────────────────────────────────

    # ── Finance & Accounting ───────────────────────────────────
    "jpmorgan", "jp-morgan", "jpmorganchase", "morganstanley", "morgan-stanley",
    "goldmansachs", "goldman-sachs", "bankofamerica", "bofa",
    "wellsfargo", "wells-fargo", "citi", "citigroup", "citibank",
    "ubs", "ubsgroup", "deutschebank", "deutsche-bank",
    "barclays", "hsbc", "santander", "bnp-paribas", "bnpparibas",
    "rbc", "td-bank", "tdbank", "scotiabank", "bmo",
    "americanexpress", "american-express", "amex", "discover", "capitalone",
    "capital-one", "synchrony", "ally", "ally-financial", "schwab",
    "fidelity", "fidelity-investments", "vanguard", "blackrock", "statestreet",
    "state-street", "northerntrust", "northern-trust", "bnymellon", "bny-mellon",
    "raymondjames", "raymond-james", "stifel", "lazard", "evercore",
    "moelis", "houlihan", "houlihan-lokey", "jefferies", "guggenheim",
    "rothschild", "perella-weinberg", "centerview",
    "blackstone", "kkr", "carlyle", "tpg", "warburg-pincus",
    "warburgpincus", "apollo", "apollo-global", "bain-capital", "baincapital",
    "advent-international", "silver-lake", "silverlake",
    "general-atlantic", "generalatlantic", "thoma-bravo", "thomabravo", "vista-equity",
    "vistaequity", "francisco-partners", "fpartners", "hellman-friedman", "permira",
    "cvc-capital", "eqt-partners",
    "bridgewater", "bridgewater-associates", "citadel", "citadelllc", "millennium",
    "two-sigma", "twosigma", "renaissance", "rentec", "de-shaw",
    "deshaw", "deshawgroup", "balyasny", "point72", "schonfeld",
    "marshall-wace", "marshallwace", "aqr", "aqr-capital", "wellington",
    "wellington-management", "pimco", "western-asset", "westernasset", "lord-abbett",
    "troweprice", "alliancebernstein", "tiaa", "voya",
    "metlife", "prudential", "newyorklife", "ny-life", "lincoln-financial",
    "principal-financial", "principal", "guardian-life",
    "chubb", "travelers", "allstate", "geico", "progressive",
    "liberty-mutual", "libertymutual", "aig", "aig-insurance", "the-hartford",
    "hartford", "marsh", "marshmclennan", "marsh-mclennan", "willis-towers-watson",
    "wtw", "aon", "gallagher", "ajg", "munich-re",
    "munichre", "swiss-re", "swissre", "berkshire-hathaway",
    "natwest", "lloyds", "standard-chartered", "macquarie",
    "kpmg", "ey", "ey-careers", "deloitte", "pwc",
    "grantthornton", "grant-thornton", "bdo", "rsm-us", "rsm",
    "crowe", "marcum", "andersen", "moss-adams",

    # ── Consulting & Strategy ──────────────────────────────────
    "mckinsey", "mckinsey-company", "bcg", "boston-consulting-group", "bain",
    "bainandcompany", "bain-and-company", "kearney", "atkearney",
    "oliver-wyman", "rolandberger", "roland-berger",
    "alvarez-marsal", "alvarezmarsal", "alixpartners",
    "fticonsulting", "fti-consulting", "huron-consulting", "huron",
    "guidehouse", "booz-allen", "boozallen", "boozallenhamilton",
    "leidos", "saic", "caci", "caci-international", "mantech",
    "accenture", "accenture-careers", "accenture-strategy", "ibm", "ibm-careers",
    "infosys", "tcs", "tata-consultancy", "wipro", "cognizant", "capgemini",
    "atos", "ntt-data", "nttdata", "dxc", "dxc-technology",
    "hcl", "hcl-tech", "tech-mahindra", "techmahindra", "ltimindtree",
    "mindtree", "ltts", "epam", "epam-systems", "globant",
    "thoughtworks", "publicis-sapient", "publicissapient", "slalom", "slalom-consulting",
    "west-monroe", "westmonroe", "north-highland", "northhighland", "point-b",

    # ── Healthcare & Clinical / Pharma ─────────────────────────
    "pfizer", "moderna", "novartis", "roche", "merck",
    "abbvie", "amgen", "gilead", "glaxosmithkline",
    "gsk", "astrazeneca", "az", "sanofi", "bayer",
    "lilly", "eli-lilly", "bristol-myers", "bms",
    "regeneron", "biogen", "vertex", "vertex-pharmaceuticals",
    "alexion", "incyte", "horizon", "jazz-pharmaceuticals",
    "alnylam", "ionis", "blueprint-medicines", "novavax", "biontech",
    "intellia", "editas", "crispr-therapeutics", "crisprtx",
    "beam-therapeutics", "denali-therapeutics", "sage-therapeutics", "neurocrine", "ultragenyx",
    "unitedhealth", "unitedhealthgroup", "uhg", "anthem", "elevance",
    "elevance-health", "humana", "centene", "cvshealth", "cvs-health",
    "molina", "molina-healthcare", "kaiserpermanente", "kaiser-permanente",
    "cigna", "evernorth", "express-scripts", "expressscripts", "optum",
    "labcorp", "quest-diagnostics", "iqvia", "iqvia-careers",
    "icon-plc", "iconplc", "parexel", "ppd", "syneos",
    "syneoshealth", "thermo-fisher", "thermofisher", "danaher", "becton-dickinson",
    "bd", "boston-scientific", "bostonscientific", "stryker", "medtronic",
    "abbott", "ge-healthcare", "siemens-healthineers", "philips",
    "philips-healthcare", "intuitive", "intuitive-surgical", "edwards-lifesciences",
    "dexcom", "insulet", "tandem-diabetes",
    "hca", "hca-healthcare", "tenet", "tenethealth", "chs",
    "ascension", "providence", "providence-health",
    "sutter", "sutterhealth", "intermountain", "mayoclinic",
    "mayo-clinic", "clevelandclinic", "cleveland-clinic", "johnshopkins",
    "mountsinai", "mount-sinai", "northwell", "northwellhealth", "newyork-presbyterian",
    "ucsf", "ucsfhealth", "stanford-health", "uclahealth", "ucla-health",
    "duke-health", "vanderbilt-health", "emory-healthcare", "emoryhealthcare",
    "pennmedicine", "penn-medicine", "michigan-medicine", "rush-health",
    "atrium-health", "trinity-health", "advocate-health",

    # ── Biotech curated ────────────────────────────────────────
    "genentech", "biomarin", "exact-sciences", "exactsciences", "guardant-health",
    "guardanthealth", "nanostring", "ginkgobio", "twist", "schrodinger",
    "recursion", "recursion-pharmaceuticals", "absci", "exscientia", "atomwise",
    "insitro", "verily", "calico",

    # ── Retail / Consumer / CPG ────────────────────────────────
    "walmart", "walmart-careers", "target", "costco", "kroger",
    "publix", "albertsons", "wholefoods", "whole-foods",
    "amazon", "amazon-jobs", "wayfair", "etsy", "ebay",
    "homedepot", "home-depot", "lowes", "best-buy", "bestbuy",
    "macys", "kohls", "nordstrom", "tjx", "tjxcompanies",
    "ross", "burlington", "dicks", "dickssportinggoods",
    "lululemon", "athleta", "underarmour", "under-armour", "nike",
    "adidas", "puma", "newbalance", "new-balance", "skechers",
    "vans", "converse", "crocs", "deckers",
    "pvh", "ralph-lauren", "ralphlauren", "tapestry", "michael-kors",
    "michaelkors", "capri-holdings", "estee-lauder", "esteelauder", "loreal",
    "l-oreal", "loreal-usa", "coty", "revlon", "elf-cosmetics",
    "ulta", "ultabeauty", "sephora", "sally-beauty",
    "bath-body-works", "victorias-secret",
    "gap", "gapinc", "old-navy", "oldnavy", "banana-republic",
    "athletic-greens", "olipop", "liquid-death", "liquiddeath",
    "magic-spoon", "graza", "fly-by-jing",
    "oatly", "beyondmeat", "beyond-meat", "impossible", "impossiblefoods",
    "chobani", "danone", "kraft-heinz", "kraftheinz",
    "general-mills", "generalmills", "kelloggs", "kellogg",
    "post-holdings", "mondelez", "mars-inc", "marsinc",
    "hershey", "hersheys", "tysonfoods", "tyson",
    "jbs", "jbsfoods", "smithfield", "perdue",
    "pepsico", "pepsi", "coca-cola", "cocacola",
    "keurig-dr-pepper", "monster-beverage", "redbull", "red-bull",
    "diageo", "ab-inbev", "anheuser-busch", "constellationbrands",
    "philip-morris", "philipmorris", "altria", "british-american-tobacco",
    "imperial-brands", "japan-tobacco",

    # ── Media & Communications ─────────────────────────────────
    "nytimes", "ny-times", "newyork-times", "wapo", "washingtonpost",
    "washington-post", "wsj", "wall-street-journal", "ft", "ftcareers",
    "bloomberg", "bloomberg-careers", "thomsonreuters", "thomson-reuters", "reuters",
    "axios", "politico", "theatlantic", "the-atlantic", "newyorker",
    "vox-media", "voxmedia", "vice", "vice-media",
    "buzzfeed-careers", "huffpost", "businessinsider", "business-insider",
    "forbes", "fortune", "cnbc", "msnbc", "nbcuniversal",
    "comcast", "disney", "thewaltdisneycompany", "warnerbros",
    "warnermedia", "wbd", "warnerbrosdiscovery",
    "paramount", "paramount-global", "amc-networks",
    "fox", "foxcorporation", "foxnews", "newscorp",
    "iheartmedia", "iheart", "siriusxm", "spotify-careers", "soundcloud",
    "tidal", "deezer", "audible", "wondery", "patreon",
    "substack", "medium", "ghost-org", "wordpress", "automattic",

    # ── Law & Government ───────────────────────────────────────
    "kirklandellis", "kirkland-ellis", "kirkland", "lathamwatkins", "latham-watkins",
    "skaddenarps", "skadden", "sullivan-cromwell", "sullivancromwell", "wachtell",
    "davispolk", "davis-polk", "simpson-thacher", "simpsonthacher", "cravath",
    "paul-weiss", "paulweiss", "weil-gotshal", "white-case",
    "whitecase", "freshfields", "linklaters", "allen-overy",
    "clifford-chance", "cliffordchance", "dentons", "baker-mckenzie",
    "norton-rose", "dlapiper", "dla-piper", "hogan-lovells",
    "ropes-gray", "ropesgray", "milbank",
    "shearman-sterling", "willkie", "willkie-farr", "morrison-foerster",
    "mofo", "wilmerhale", "covington-burling", "gibson-dunn",
    "fbi-careers", "doj", "doj-careers", "state-department",
    "dod", "dod-careers", "darpa", "iarpa", "nsa", "cia",
    "epa", "epa-careers", "fcc", "fda", "cdc", "nih",
    "nasa", "nasa-careers", "nps", "us-postal-service", "usps",
    "tva", "energy-gov", "doe", "department-of-energy",
    "irs", "occ", "fed", "federal-reserve", "sec-gov",
    "world-bank", "worldbank", "imf", "un-careers", "unicef",
    "wfp", "unhcr", "unesco", "ilo", "wto",
    "oecd", "americorps", "peace-corps", "peacecorps",

    # ── Education & EdTech ─────────────────────────────────────
    "harvard", "yale", "stanford", "princeton", "mit",
    "cornell", "columbia", "upenn", "brown-university",
    "dartmouth", "uchicago", "northwestern", "duke", "nyu",
    "berkeley", "uc-berkeley", "ucla", "usc", "umich",
    "umichigan", "unc", "uva", "georgetown", "vanderbilt",
    "rice", "emory", "wustl", "carnegiemellon", "carnegie-mellon",
    "cmu", "caltech", "jhu",
    "byjus", "pearson", "mcgraw-hill", "mcgrawhill",
    "scholastic", "wileyplus", "wiley", "cengage", "chegg",
    "varsity-tutors", "varsitytutors", "quizlet", "edx",
    "udacity", "udemy", "skillshare", "futurelearn",
    "schoolmint", "renaissance-learning", "illuminate-education",
    "powerschool", "blackboard", "instructure", "canvaslms",
    "schoology", "newschools", "summit-learning",

    # ── Energy / Climate / Cleantech ───────────────────────────
    "exxonmobil", "exxon", "exxon-mobil", "chevron", "chevroncareers",
    "shell", "shelloil", "bp", "totalenergies", "total-energies",
    "equinor", "eni", "petrobras", "saudiaramco", "aramco",
    "conocophillips", "conoco-phillips", "marathon-petroleum", "valero",
    "phillips66", "phillips-66", "occidental", "oxy", "halliburton",
    "schlumberger", "slb", "baker-hughes", "bakerhughes",
    "duke-energy", "dukeenergy", "nexteraenergy", "nextera-energy", "southerncompany",
    "southern-company", "exelon", "dominion-energy", "ppl",
    "edison-international", "consolidated-edison", "coned", "national-grid",
    "iberdrola", "enel", "engie", "edf",
    "tesla", "tesla-careers", "rivian", "lucid", "polestar",
    "fisker", "lordstown", "canoo", "nikola", "hyzon",
    "chargepoint", "evgo", "blink-charging", "wallbox",
    "enphase", "enphase-energy", "sunrun", "sunpower", "sunnova",
    "first-solar", "firstsolar", "canadian-solar", "ja-solar",
    "trinasolar", "longi", "qcells", "hanwha-qcells",
    "vestas", "siemens-gamesa", "ge-vernova",
    "form-energy", "fluence-energy", "8minute-solar",
    "primergy", "lightsource-bp", "longroad-energy",

    # ── Manufacturing / Aerospace ──────────────────────────────
    "boeing", "boeing-careers", "lockheedmartin", "lockheed-martin", "raytheon",
    "rtx", "northrop", "northropgrumman", "northrop-grumman",
    "general-dynamics", "generaldynamics", "bae-systems", "baesystems",
    "spacex", "blue-origin", "blueorigin", "rocketlab", "rocket-lab",
    "relativity-space", "anduril", "anduril-industries", "shield-ai",
    "skydio", "saildrone", "kratos",
    "honeywell", "ge-aerospace", "geaerospace", "rolls-royce", "rollsroyce",
    "pratt-whitney", "spirit-aerosystems", "textron",
    "embraer", "bombardier", "airbus", "leonardodrs",
    "caterpillar", "cat", "deere", "johndeere", "agco",
    "cnh-industrial", "kubota", "komatsu",
    "hitachi", "abb", "siemens",
    "ge-power", "schneider-electric", "schneiderelectric", "eaton",
    "rockwell-automation", "emerson", "honeywell-aerospace",
    "parker-hannifin", "illinois-tool-works", "itw", "dover-corp",
    "fortive", "ametek", "ingersoll-rand",
    "snap-on", "snapon",
    "ford", "fordmotor", "gm", "general-motors", "stellantis",
    "honda", "toyota", "nissan", "subaru", "mazda",
    "hyundai", "kia", "vw", "volkswagen", "audi",
    "bmw", "mercedes-benz", "daimler", "porsche", "volvocars",
    "jaguar-landrover", "ferrari", "lamborghini", "mclaren",

    # ── Real Estate / PropTech / Construction ──────────────────
    "cbre", "jll", "joneslanglasalle", "cushmanwakefield", "cushman-wakefield",
    "colliers", "newmark", "savills",
    "marcus-millichap", "crexi", "loopnet", "yardi",
    "appfolio", "buildium", "rentmanager", "entrata",
    "realpage", "blueground", "common-living",
    "redfin", "zillow", "trulia", "realtor-com",
    "rocketcompanies", "rocket-companies", "rocketmortgage",
    "loandepot", "better-mortgage", "blend",
    "kw", "keller-williams", "kellerwilliams", "remax", "re-max",
    "skanska", "turner-construction", "turnerconstruction", "bechtel",
    "fluor", "kbr", "jacobs", "jacobs-engineering",
    "aecom", "wsp", "stantec", "tetra-tech",
    "brookfield", "prologis",

    # ── Marketing / Advertising / Agencies ─────────────────────
    "wpp", "wppgroup", "omnicom", "omnicomgroup", "publicis",
    "publicis-groupe", "ipg", "interpublic", "dentsu",
    "havas", "stagwell", "epsilon", "merkle",
    "razorfish", "vmly-r", "vmlyr", "wunderman-thompson",
    "mccann", "ddb", "tbwa",
    "bbdo", "leoburnett", "leo-burnett", "saatchi",
    "ogilvy", "wieden-kennedy", "wk",
    "rga", "r-ga", "horizon-media", "spark-foundry",
    "edelman", "weber-shandwick", "ketchum", "fleishman-hillard",
    "burson-cohn", "hill-knowlton", "golin",

    # ── Travel / Hospitality / Restaurants ─────────────────────
    "marriott", "marriott-international", "hilton", "hilton-hotels", "hyatt",
    "hyatt-hotels", "ihg", "intercontinental", "wyndham",
    "accor", "fourseasons", "four-seasons",
    "mandarin-oriental", "ritz-carlton", "stregis", "rosewood",
    "loews-hotels",
    "americanairlines", "american-airlines", "united-airlines", "unitedairlines", "delta",
    "delta-airlines", "southwest-airlines", "southwestairlines", "jetblue", "alaska-airlines",
    "spirit-airlines", "frontier-airlines", "hawaiian-airlines",
    "fedex", "ups", "amazon-air", "dhl", "dhl-express",
    "carmax", "enterprise-holdings", "hertz", "avis-budget", "sixt",
    "expedia", "expedia-group", "booking-holdings",
    "tripadvisor", "trip-com", "kayak", "agoda", "skyscanner",
    "vrbo", "homeaway", "vacasa",
    "doordash-careers", "ubereats", "instacart-careers",
    "grubhub", "postmates", "olo", "toast-careers",
    "shake-shack", "shakeshack", "chipotle", "sweetgreen-careers",
    "cava", "panera", "starbucks", "dominos", "domino-pizza",
    "papa-johns", "papajohns", "wendys", "mcdonalds", "burger-king",
    "yum-brands", "yumbrands", "kfc", "tacobell", "pizza-hut",
    "darden", "olive-garden", "applebees", "ihop",
    "cracker-barrel",

    # ── Telecom & Networking ───────────────────────────────────
    "verizon", "verizon-careers", "att", "atandt", "tmobile",
    "t-mobile", "comcast-careers", "charter", "spectrum",
    "cox-communications", "altice-usa",
    "frontier-communications", "centurylink", "lumen", "lumen-technologies",
    "windstream",
    "cisco", "cisco-systems", "juniper", "juniper-networks",
    "arista", "arista-networks", "extreme-networks",
    "f5", "f5-networks", "palo-alto-networks",
    "paloaltonetworks", "fortinet", "fortinet-careers", "checkpoint", "check-point",
    "sonicwall", "barracuda", "trellix",
    "mcafee", "norton", "nortonlifelock", "kaspersky",
    "trendmicro", "trend-micro", "bitdefender", "eset", "sophos",
    "crowdstrike", "sentinelone", "cybereason", "darktrace",
    "tenable", "rapid7", "qualys", "tanium", "varonis",

    # ── Logistics / Supply Chain ──────────────────────────────
    "fedex-careers", "ups-careers", "amazon-logistics", "xpo", "xpo-logistics",
    "chrobinson", "ch-robinson", "expeditors", "kuehne-nagel",
    "dhl-supply-chain", "dsv", "ryder", "ryder-system",
    "schneider-trucking", "knight-swift", "knightswift",
    "jbhunt", "jb-hunt", "old-dominion", "olddominion", "saia",
    "yellow-corporation", "werner-enterprises",
    "covenant-logistics", "matson",

    # ── Sports / Fitness ──────────────────────────────────────
    "nba", "nfl", "mlb", "nhl", "wnba", "mls",
    "espn", "fox-sports", "foxsports", "barstool",
    "wwe", "ufc", "topgolf",
    "lifetime-fitness", "equinox", "soulcycle", "barrys-bootcamp",
    "orangetheory", "f45", "club-pilates",
    "planet-fitness", "24-hour-fitness", "snapfitness",
    "anytime-fitness", "crunch-fitness",

    # ── Cybersecurity / Identity ──────────────────────────────
    "snowflake-careers", "okta-careers", "1password", "1password-careers", "lastpass",
    "dashlane", "bitwarden", "keeper", "keepersecurity", "duo-security",
    "yubico", "auth0", "authzero", "stytch",
    "clerk-dev", "clerkdev", "nextauth", "supertokens",
    "kasada", "perimeterx", "humansecurity", "wiz",
    "lacework", "orca-security", "snyk-security",
    "veracode", "checkmarx", "synopsys-software", "blackduck",
    "thales", "thales-group", "rsa-security",

    # ── Nonprofit / NGO ───────────────────────────────────────
    "redcross", "americanredcross", "salvation-army", "salvationarmy", "habitat-humanity",
    "habitatforhumanity", "unitedway", "united-way", "ymca", "ywca",
    "make-a-wish", "makeawish", "stjude", "st-jude",
    "doctors-without-borders", "doctorswithoutborders", "msf", "save-the-children",
    "world-vision", "worldvision", "worldwildlifefund", "wwf", "natureconservancy",
    "sierraclub", "sierra-club", "edf", "environmental-defense",
    "ucsusa", "wri", "world-resources",
    "carbon180", "rmi", "rocky-mountain-institute", "ceres",
    "robertwoodjohnson", "rwjf", "ford-foundation",
    "fordfoundation", "rockefeller-foundation", "macarthur-foundation",
    "knight-foundation", "openphilanthropy", "open-philanthropy",
    "givewell", "give-directly", "givedirectly", "evidence-action",

    # ── Aviation / Defense Engineering ────────────────────────
    "garmin", "garmin-careers", "trimble", "raytheonbbn",
    "lawrence-livermore", "los-alamos", "sandia-labs", "sandialabs",
    "oak-ridge", "oakridge", "fermilab", "argonne",
    "berkeley-lab", "brookhaven", "slac", "jpl",
    "jet-propulsion-lab", "aerospace-corp", "mitre", "mitrecorp",
    "rand", "rand-corporation", "ida",
    "draper-laboratory", "lincoln-laboratory", "battelle", "noblis",
]
