"""Dilly agent action types and stake definitions."""

from __future__ import annotations

from typing import Literal

DillyAction = Literal[
    "CREATE_DEADLINE",
    "UPDATE_DEADLINE",
    "DELETE_DEADLINE",
    "CREATE_SUB_DEADLINE",
    "CREATE_ACTION_ITEM",
    "COMPLETE_ACTION_ITEM",
    "DELETE_ACTION_ITEM",
    "SNOOZE_ACTION_ITEM",
    "UPDATE_CAREER_GOAL",
    "ADD_TARGET_COMPANY",
    "REMOVE_TARGET_COMPANY",
    "UPDATE_MAJOR",
    "UPDATE_TRACK",
    "UPDATE_JOB_LOCATIONS",
    "UPDATE_APPLICATION_TARGET",
    "CREATE_APPLICATION",
    "UPDATE_APPLICATION_STATUS",
    "DELETE_APPLICATION",
    "ADD_APPLICATION_NOTE",
    "TRIGGER_AUDIT",
    "SAVE_BULLET_REWRITE",
    "SAVE_RESUME_NOTE",
]

ALL_ACTIONS: set[str] = {
    "CREATE_DEADLINE",
    "UPDATE_DEADLINE",
    "DELETE_DEADLINE",
    "CREATE_SUB_DEADLINE",
    "CREATE_ACTION_ITEM",
    "COMPLETE_ACTION_ITEM",
    "DELETE_ACTION_ITEM",
    "SNOOZE_ACTION_ITEM",
    "UPDATE_CAREER_GOAL",
    "ADD_TARGET_COMPANY",
    "REMOVE_TARGET_COMPANY",
    "UPDATE_MAJOR",
    "UPDATE_TRACK",
    "UPDATE_JOB_LOCATIONS",
    "UPDATE_APPLICATION_TARGET",
    "CREATE_APPLICATION",
    "UPDATE_APPLICATION_STATUS",
    "DELETE_APPLICATION",
    "ADD_APPLICATION_NOTE",
    "TRIGGER_AUDIT",
    "SAVE_BULLET_REWRITE",
    "SAVE_RESUME_NOTE",
}

LOW_STAKES: set[str] = {
    "CREATE_DEADLINE",
    "CREATE_SUB_DEADLINE",
    "CREATE_ACTION_ITEM",
    "COMPLETE_ACTION_ITEM",
    "SNOOZE_ACTION_ITEM",
    "ADD_TARGET_COMPANY",
    "CREATE_APPLICATION",
    "ADD_APPLICATION_NOTE",
    "SAVE_BULLET_REWRITE",
    "SAVE_RESUME_NOTE",
    "TRIGGER_AUDIT",
}

