/**
 * Approved UTampa majors — single source of truth.
 * Used by both the major and minor tag-input fields on the profile screen.
 * No value outside this list may be submitted.
 */
export const APPROVED_MAJORS: readonly string[] = [
  "Accounting",
  "Advertising and Public Relations",
  "Allied Health",
  "Biochemistry",
  "Biology",
  "Business Administration",
  "Chemistry",
  "Communication",
  "Computer Information Systems",
  "Computer Science",
  "Criminal Justice",
  "Cybersecurity",
  "Data Science",
  "Digital Arts and Design",
  "Economics",
  "Education",
  "English",
  "Environmental Science",
  "Exercise Science",
  "Finance",
  "Forensic Science",
  "Government and World Affairs",
  "Health Sciences",
  "History",
  "Information Technology",
  "International Business",
  "Journalism",
  "Kinesiology",
  "Liberal Arts",
  "Management",
  "Marine Science",
  "Marketing",
  "Mathematics",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Pre-Medicine",
  "Psychology",
  "Public Health",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Sport Management",
  "Theatre Arts",
] as const;

export const APPROVED_MAJORS_SET = new Set<string>(APPROVED_MAJORS);
