/**
 * @dilly/api — Shared data layer for all Dilly frontends
 *
 * Import from here for everything:
 *   import { createDillyClient, type AuditV2, getScoreColor } from '@dilly/api';
 */

// Client
export {
  createDillyClient,
  localStorageTokenProvider,
  DillyApiError,
  type DillyClient,
  type DillyClientOptions,
  type TokenProvider,
} from "./client";

// Types — complete re-export so consumers can import anything from "@dilly/api"
export type {
  ActionItem,
  ApiError,
  AppProfile,
  Application,
  ApplicationStatus,
  ATSInfo,
  ATSStrictness,
  AuditHistorySummary,
  AuditHistorySummaryRow,
  AuditRecommendation,
  AuditV2,
  AuthSendCodeResponse,
  AuthUser,
  AuthVerifyCodeResponse,
  AutomationRisk,
  BulletComparisonPayload,
  CareerPlaybookDeepDive,
  CareerPlaybookPayload,
  CareerPlaybookSignal,
  ChatMessage,
  ChatMode,
  CohortComparisonPayload,
  CohortPulse,
  CohortScore,
  ConversationOutput,
  DetectedDeadline,
  DillyDeadline,
  DillyNotification,
  DillySubDeadline,
  DimensionKey,
  DimensionScores,
  InterviewChecklistPayload,
  MainAppTab,
  MemoryAction,
  MemoryCategory,
  MemoryConfidence,
  MemoryItem,
  MemorySource,
  MilestoneType,
  ProfileAchievements,
  ProfileThemeId,
  ReadyCheck,
  ReadyCheckAction,
  ReadyCheckVerdict,
  Rec,
  RecommendationType,
  RichContext,
  RiskProfile,
  ScoreBreakdownPayload,
  ScoreImpactEstimate,
  SessionCapture,
  SummaryLine,
  TimelineEvent,
  TimelinePayload,
  User,
  UserCohortPulse,
  VisualPayload,
  VisualType,
  VoiceConversation,
  VoiceConvo,
  VoiceMockTurn,
  VoiceMockTurnDisplay,
  VoiceTone,
} from "./types";

// Scores
export {
  getScoreBand,
  getScoreColor,
  getScoreLabel,
  getScoreBg,
  getScoreBorder,
  getScoreCardBg,
  getMilestone,
  DIMENSIONS,
  type ScoreBand,
} from "./scores";

// Storage keys
export {
  AUDIT_RESULT_KEY,
  AUTH_TOKEN_KEY,
  AUTH_USER_CACHE_KEY,
  AUTH_USER_CACHE_MAX_AGE_MS,
  AUTH_USER_KEY,
  DESKTOP_AUTH_TOKEN_KEY,
  DILLY_AUDIT_REPORT_HANDOFF_KEY,
  DILLY_EXPAND_JOB_SEARCH_VOICE_PROMPT_KEY,
  DILLY_JOB_GAP_VOICE_PROMPT_KEY,
  DILLY_LAST_ATS_SCORE_KEY,
  DILLY_LEADERBOARD_REFRESH_KEY,
  DILLY_LEADERBOARD_VOICE_PROMPT_KEY,
  DILLY_OPEN_OVERLAY_KEY,
  DILLY_PLAYBOOK_VOICE_PROMPT_KEY,
  DILLY_SCORE_GAP_VOICE_PROMPT_KEY,
  DILLY_SCORE_HISTORY_KEY,
  DILLY_STORAGE_KEY_BASE,
  HAS_ONBOARDED_KEY,
  ONBOARDING_COHORT_KEY,
  ONBOARDING_INDUSTRY_TARGET_KEY,
  ONBOARDING_MAJORS_KEY,
  ONBOARDING_NAME_KEY,
  ONBOARDING_PRE_PROF_KEY,
  ONBOARDING_STEP_KEY,
  ONBOARDING_TARGET_KEY,
  ONBOARDING_TRACK_KEY,
  PENDING_UPLOAD_KEY,
  PENDING_VOICE_KEY,
  PROFILE_CACHE_KEY_BASE,
  RECRUITER_API_KEY_STORAGE,
  SCHOOL_NAME_KEY,
  SCHOOL_STORAGE_KEY,
  VOICE_CONVOS_KEY,
  VOICE_FROM_AUDIT_ID_KEY,
  VOICE_FROM_CERT_HANDOFF_KEY,
  VOICE_MESSAGES_KEY,
} from "./storage-keys";

// Constants
export {
  ALL_COHORTS,
  APPROVED_MAJORS,
  COHORT_COLORS,
  colors,
  detectCohort,
  getAutomationRisk,
  getCohortColor,
  INTERESTS_LIST,
  MAJOR_TO_COHORT,
  PRE_PROF_OPTIONS,
  PRE_PROF_TO_COHORT,
  type CohortName,
} from "./constants";
