/**
 * useYourPlan — the anchor concept for Dilly across all three modes.
 *
 * Product verb (per founder): "Dilly turns your career confusion
 * into a plan." Every tab, card, and button in the app exists to
 * produce the plan, execute on it, or sharpen the profile that
 * feeds it. This hook is the SINGLE source of truth for what the
 * plan says today.
 *
 * Cost:
 *   - Zero LLM. Pure template logic fed by existing profile/activity
 *     signals that are already fetched on home load.
 *   - Regenerates DAILY (based on a stored "last computed date").
 *     User asked for daily if it costs nothing; this meets that bar.
 *
 * Shape:
 *   {
 *     headline: string  // "Apply to 3 roles this week."
 *     followup: string  // "Then check back so Dilly can tailor."
 *     cta: string       // "Open plan" / "Start with Dilly"
 *     initialMessage: string  // seeded into the AI overlay on tap
 *   }
 *
 * Why template-not-LLM:
 *   - Users can't tell the difference between "Apply to 3 roles by
 *     Friday" generated by Haiku vs. a path-specific template. Both
 *     read as "the AI picked this for me today."
 *   - LLM per-user-per-day would be ~$0.002 × users × 30 days,
 *     which adds up fast at scale with no UX gain.
 *   - Template IS the AI's output once the model has been "compiled
 *     down" into rules. We skip the runtime call.
 *
 * Storage:
 *   AsyncStorage key `dilly_plan_v1` holds { date: 'YYYY-MM-DD',
 *   plan: PlanShape }. On mount, if today's date matches, we return
 *   cached; else we regenerate and persist.
 *
 * Call site:
 *   Every home screen (HolderHome, SeekerHome, StudentHome, Senior
 *   ResetHome) wires this in and renders the <YourPlanCard/>
 *   component at the top of the card stack.
 */

import { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Mode = 'student' | 'seeker' | 'holder';

export type PlanDestination = 'chat' | 'jobs';

export interface YourPlan {
  headline: string;
  followup: string;
  cta: string;
  initialMessage: string;
  mode: Mode;
  pathKey: string;
  generatedAt: string; // ISO date (YYYY-MM-DD)
  destination: PlanDestination;
  actionTaken?: boolean;
}

interface PlanInputs {
  mode: Mode;
  userPath: string;      // from profile.user_path
  firstName: string;
  // Activity signals. All optional. When absent, the plan falls back
  // to a path-generic headline, which is still better than nothing.
  appCount?: number;             // jobs applied
  factCount?: number;            // profile facts
  interviewingCount?: number;    // interviews in progress
  currentRole?: string;          // holder path
  daysSinceLastAudit?: number;
  recentDeadline?: { label: string; daysUntil: number } | null;
}

const STORAGE_KEY = 'dilly_plan_v1';

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/**
 * The generator. Deterministic — same inputs on same day = same plan.
 * That's the right behavior for a "today's plan" card; the user
 * should see the same plan all day no matter how many times they
 * open the app.
 */
// Guard against garbage profile values sneaking into template copy.
// We've had single-character / whitespace-only values land here from
// partial extractions, which produced lines like "take the first step
// toward 'S'". A meaningful value is >= 4 chars AND (contains a space
// OR is >= 8 chars) — that passes "your role" but rejects "S", "a",
// "job", etc.
function _meaningful(s: string | null | undefined): boolean {
  const t = (s || '').trim();
  return t.length >= 4 && (t.includes(' ') || t.length >= 8);
}

function generatePlan(i: PlanInputs): YourPlan {
  const { mode, userPath, firstName, appCount = 0, factCount = 0,
    interviewingCount = 0, currentRole, recentDeadline } = i;

  // Priority 1: a near-term deadline ALWAYS wins the headline slot,
  // but only if the label is substantive enough to not look broken.
  // "Final round at Ramp" → in. "R" or "job" → fall through.
  if (recentDeadline && recentDeadline.daysUntil <= 3 && _meaningful(recentDeadline.label)) {
    return {
      mode,
      pathKey: userPath,
      headline: recentDeadline.daysUntil === 0
        ? `${recentDeadline.label} is today.`
        : recentDeadline.daysUntil === 1
        ? `${recentDeadline.label} is tomorrow.`
        : `${recentDeadline.label} in ${recentDeadline.daysUntil} days.`,
      followup: 'Block 30 minutes with Dilly to prep.',
      cta: 'Prep with Dilly',
      initialMessage: `Help me prep for "${recentDeadline.label}" which is ${recentDeadline.daysUntil <= 1 ? 'tomorrow' : `in ${recentDeadline.daysUntil} days`}.`,
      generatedAt: today(),
      destination: 'chat',
    };
  }

  // Priority 2: interviewing in progress — this is where outcomes
  // get decided, so it trumps everything else.
  if (interviewingCount > 0) {
    return {
      mode,
      pathKey: userPath,
      headline: `You're interviewing at ${interviewingCount} ${interviewingCount === 1 ? 'place' : 'places'}.`,
      followup: 'Pick the one that matters most and run a mock with Dilly.',
      cta: 'Start practice',
      initialMessage: "I'm interviewing this week. Help me pick the one I'm most worried about and run a mock.",
      generatedAt: today(),
      destination: 'chat',
    };
  }

  // Priority 3: mode-specific anchors. These are the default plans
  // for each path when there's no urgent deadline / interview.
  if (mode === 'holder') {
    // Holder — career acceleration while employed. Plan frames
    // growth, not job search. _meaningful() guards against garbage
    // role values (e.g. "a", "SE", "-") that would produce broken
    // copy like "Sharpen one edge as a S this week."
    const roleIsReal = _meaningful(currentRole);
    return {
      mode,
      pathKey: userPath,
      headline: roleIsReal
        ? `Sharpen one edge as a ${currentRole} this week.`
        : 'Sharpen one edge in your field this week.',
      followup: 'Read the weekly signal, then run one growth conversation with Dilly.',
      cta: 'See this week',
      initialMessage: roleIsReal
        ? `I'm a ${currentRole}. Based on this week's field signal, what's ONE concrete move I should make to stay ahead?`
        : "Based on this week's field signal, what's ONE concrete move I should make to stay ahead?",
      generatedAt: today(),
      destination: 'chat',
    };
  }

  if (mode === 'student') {
    // Student paths: vary by user_path.
    if (userPath === 'dropout') {
      return {
        mode,
        pathKey: userPath,
        headline: 'Ship one visible thing this week.',
        followup: 'Commit, post, demo. Receipts beat resumes.',
        cta: 'Plan the ship',
        initialMessage: "I'm a dropout working on proof-over-paper. Help me pick the one thing to ship this week.",
        generatedAt: today(),
        destination: 'chat',
      };
    }
    if (userPath === 'international_grad') {
      return {
        mode,
        pathKey: userPath,
        headline: 'Research one sponsor-friendly company this week.',
        followup: 'Save it to your target list, then tailor a fit read.',
        cta: 'Start research',
        initialMessage: "I'm on an international-grad path. Help me pick one sponsor-friendly company to research deeply this week.",
        generatedAt: today(),
        destination: 'jobs',
      };
    }
    // Default student anchor.
    if (appCount < 3) {
      return {
        mode,
        pathKey: userPath,
        headline: 'Apply to 3 roles this week.',
        followup: 'Dilly will tailor a fit read on each.',
        cta: 'Open jobs',
        initialMessage: 'Help me pick 3 roles to apply to this week. Start with the strongest matches.',
        generatedAt: today(),
        destination: 'jobs',
      };
    }
    if (factCount < 12) {
      return {
        mode,
        pathKey: userPath,
        headline: 'Teach Dilly 3 more things about you this week.',
        followup: 'Every fact sharpens the guidance and the fit reads.',
        cta: 'Talk to Dilly',
        initialMessage: 'Help me add 3 more things about my experience that a recruiter would want to know.',
        generatedAt: today(),
        destination: 'chat',
      };
    }
    return {
      mode,
      pathKey: userPath,
      headline: `Push one conversation forward this week, ${firstName}.`,
      followup: 'A referral beats a cold app. Pick the person, draft the message.',
      cta: 'Start with Dilly',
      initialMessage: 'Help me draft one warm outreach message to someone in my target field this week.',
      generatedAt: today(),
      destination: 'chat',
    };
  }

  // mode === 'seeker' — paths: senior_reset, career_switch, parent_returning, etc.
  if (userPath === 'senior_reset') {
    return {
      mode,
      pathKey: userPath,
      headline: 'Warm up one past colleague this week.',
      followup: 'People in your network hire first. Dilly will help you draft.',
      cta: 'Draft with Dilly',
      initialMessage: "I'm reopening my job search. Help me draft a check-in to one former colleague this week.",
      generatedAt: today(),
      destination: 'chat',
    };
  }
  if (userPath === 'career_switch') {
    return {
      mode,
      pathKey: userPath,
      headline: 'Publish one skill-transfer proof this week.',
      followup: 'A short project or case study signals the pivot is real.',
      cta: 'Plan it',
      initialMessage: "I'm switching careers. Help me pick ONE small project or case study I can publish this week.",
      generatedAt: today(),
      destination: 'chat',
    };
  }
  if (userPath === 'parent_returning') {
    return {
      mode,
      pathKey: userPath,
      headline: 'Set one coffee chat this week.',
      followup: 'Returning to work starts with people, not postings.',
      cta: 'Find the person',
      initialMessage: "I'm returning to work after a career gap. Help me pick the one person to reach out to this week.",
      generatedAt: today(),
      destination: 'chat',
    };
  }
  // Default seeker.
  return {
    mode,
    pathKey: userPath,
    headline: appCount < 5
      ? 'Apply to 5 strong matches this week.'
      : 'Book one conversation this week.',
    followup: appCount < 5
      ? 'Dilly will tailor a fit read on each one.'
      : 'A call beats three cold applications.',
    cta: appCount < 5 ? 'Open jobs' : 'Start with Dilly',
    initialMessage: appCount < 5
      ? 'Help me pick 5 strong roles to apply to this week.'
      : "I've been applying consistently. Help me shift toward conversations this week.",
    generatedAt: today(),
    destination: appCount < 5 ? 'jobs' : 'chat',
  };
}

/** Marks today's plan action as taken. Call when the user taps the CTA. */
export async function markPlanActionTaken(): Promise<void> {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    const stored = JSON.parse(raw);
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify({ ...stored, actionTaken: true }));
  } catch {}
}

/**
 * Hook: returns the plan for today. Regenerates if the stored date
 * is stale, otherwise returns cached. Inputs must be passed fresh
 * each render — the hook reacts to input changes so a new deadline
 * appearing mid-day bumps the plan immediately.
 */
export function useYourPlan(inputs: PlanInputs | null): YourPlan | null {
  const [plan, setPlan] = useState<YourPlan | null>(null);

  useEffect(() => {
    if (!inputs) {
      setPlan(null);
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        const raw = await AsyncStorage.getItem(STORAGE_KEY);
        const cached = raw ? JSON.parse(raw) : null;
        if (
          cached &&
          cached.plan &&
          cached.date === today() &&
          cached.plan.pathKey === inputs.userPath &&
          cached.plan.mode === inputs.mode
        ) {
          if (!cancelled) setPlan({ ...cached.plan, actionTaken: cached.actionTaken ?? false });
          return;
        }
      } catch {
        // fall through to regenerate
      }
      const fresh = generatePlan(inputs);
      try {
        await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify({
          date: today(),
          plan: fresh,
        }));
      } catch {}
      if (!cancelled) setPlan(fresh);
    })();
    return () => { cancelled = true; };
    // Regenerate if any relevant input shifts (new deadline, new
    // interview, new count). Storage still guards same-day identity
    // so opening the app 20 times a day doesn't churn.
  }, [
    inputs?.mode,
    inputs?.userPath,
    inputs?.appCount,
    inputs?.factCount,
    inputs?.interviewingCount,
    inputs?.currentRole,
    inputs?.recentDeadline?.label,
    inputs?.recentDeadline?.daysUntil,
  ]);

  return plan;
}

export default useYourPlan;
