/**
 * useYourPlan - the anchor concept for Dilly across all three modes.
 *
 * Product verb (per founder): "Dilly turns your career confusion
 * into a plan." Every tab, card, and button in the app exists to
 * produce the plan, execute on it, or sharpen the profile that
 * feeds it. This hook is the SINGLE source of truth for what the
 * plan says today.
 *
 * Cost:
 *   - Zero LLM. Pure template logic fed by existing profile/activity
 *     signals that are already fetched on home load.
 *   - Regenerates DAILY (based on a stored "last computed date").
 *     User asked for daily if it costs nothing; this meets that bar.
 *
 * Shape:
 *   {
 *     headline: string  // "Apply to 3 roles this week."
 *     followup: string  // "Then check back so Dilly can tailor."
 *     cta: string       // "Open plan" / "Start with Dilly"
 *     initialMessage: string  // seeded into the AI overlay on tap
 *   }
 *
 * Why template-not-LLM:
 *   - Users can't tell the difference between "Apply to 3 roles by
 *     Friday" generated by Haiku vs. a path-specific template. Both
 *     read as "the AI picked this for me today."
 *   - LLM per-user-per-day would be ~$0.002 × users × 30 days,
 *     which adds up fast at scale with no UX gain.
 *   - Template IS the AI's output once the model has been "compiled
 *     down" into rules. We skip the runtime call.
 *
 * Storage:
 *   AsyncStorage key `dilly_plan_v1` holds { date: 'YYYY-MM-DD',
 *   plan: PlanShape }. On mount, if today's date matches, we return
 *   cached; else we regenerate and persist.
 *
 * Call site:
 *   Every home screen (HolderHome, SeekerHome, StudentHome, Senior
 *   ResetHome) wires this in and renders the <YourPlanCard/>
 *   component at the top of the card stack.
 */

import { useCallback, useEffect, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Mode = 'student' | 'seeker' | 'holder';

export type PlanDestination = 'chat' | 'jobs';

export interface YourPlan {
  headline: string;
  followup: string;
  cta: string;
  initialMessage: string;
  mode: Mode;
  pathKey: string;
  generatedAt: string; // ISO date (YYYY-MM-DD)
  destination: PlanDestination;
  actionTaken?: boolean;
}

interface PlanInputs {
  mode: Mode;
  userPath: string;      // from profile.user_path
  firstName: string;
  // Activity signals. All optional. When absent, the plan falls back
  // to a path-generic headline, which is still better than nothing.
  appCount?: number;             // jobs applied
  factCount?: number;            // profile facts
  interviewingCount?: number;    // interviews in progress
  currentRole?: string;          // holder path
  daysSinceLastAudit?: number;
  recentDeadline?: { label: string; daysUntil: number } | null;
}

const STORAGE_KEY = 'dilly_plan_v1';

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/**
 * The generator. Deterministic - same inputs on same day = same plan.
 * That's the right behavior for a "today's plan" card; the user
 * should see the same plan all day no matter how many times they
 * open the app.
 */
// Guard against garbage profile values sneaking into template copy.
// We've had single-character / whitespace-only values land here from
// partial extractions, which produced lines like "take the first step
// toward 'S'". A meaningful value is >= 4 chars AND (contains a space
// OR is >= 8 chars) - that passes "your role" but rejects "S", "a",
// "job", etc.
function _meaningful(s: string | null | undefined): boolean {
  const t = (s || '').trim();
  return t.length >= 4 && (t.includes(' ') || t.length >= 8);
}

function generatePlanVariants(i: PlanInputs): YourPlan[] {
  const { mode, userPath, firstName, appCount = 0, factCount = 0,
    interviewingCount = 0, currentRole, recentDeadline } = i;

  const base = (overrides: Partial<YourPlan>): YourPlan => ({
    mode,
    pathKey: userPath,
    headline: '',
    followup: '',
    cta: '',
    initialMessage: '',
    destination: 'chat',
    generatedAt: today(),
    ...overrides,
  });

  // Pinned variants - when truly urgent, these always go first so a
  // user with a deadline / live interview never rotates past them.
  const pinned: YourPlan[] = [];

  if (recentDeadline && recentDeadline.daysUntil <= 3 && _meaningful(recentDeadline.label)) {
    pinned.push(base({
      headline: recentDeadline.daysUntil === 0
        ? `${recentDeadline.label} is today.`
        : recentDeadline.daysUntil === 1
        ? `${recentDeadline.label} is tomorrow.`
        : `${recentDeadline.label} in ${recentDeadline.daysUntil} days.`,
      followup: 'Block 30 minutes with Dilly to prep.',
      cta: 'Prep with Dilly',
      initialMessage: `Help me prep for "${recentDeadline.label}" which is ${recentDeadline.daysUntil <= 1 ? 'tomorrow' : `in ${recentDeadline.daysUntil} days`}.`,
    }));
  }

  if (interviewingCount > 0) {
    pinned.push(base({
      headline: `You're interviewing at ${interviewingCount} ${interviewingCount === 1 ? 'place' : 'places'}.`,
      followup: 'Pick the one that matters most and run a mock with Dilly.',
      cta: 'Start practice',
      initialMessage: "I'm interviewing this week. Help me pick the one I'm most worried about and run a mock.",
    }));
  }

  // Mode/path-specific rotation pool. The user cycles through these
  // each time they tap the card and return to home. Order is
  // intentional: highest-leverage variant first so even a one-tap user
  // gets the strongest move.
  const pool: YourPlan[] = [];

  if (mode === 'holder') {
    const roleIsReal = _meaningful(currentRole);
    const role = roleIsReal ? currentRole! : 'your field';
    pool.push(base({
      headline: roleIsReal
        ? `Sharpen one edge as a ${role} this week.`
        : 'Sharpen one edge in your field this week.',
      followup: 'Read the weekly signal, then run one growth conversation with Dilly.',
      cta: 'See this week',
      initialMessage: `I'm a ${role}. Based on this week's field signal, what's ONE concrete move I should make to stay ahead?`,
    }));
    pool.push(base({
      headline: 'Reach out to one mentor this week.',
      followup: 'Growth compounds through people who already did what you want to do.',
      cta: 'Draft with Dilly',
      initialMessage: 'Help me draft a check-in to one mentor or senior peer this week.',
    }));
    pool.push(base({
      headline: 'Pick one skill to level up this month.',
      followup: 'Dilly will turn it into a 4-week plan you can actually finish.',
      cta: 'Plan it',
      initialMessage: 'Help me pick ONE skill to level up over the next 4 weeks based on where my field is headed.',
    }));
    pool.push(base({
      headline: 'Audit your visibility at work this week.',
      followup: "Promotion comes from being seen on the right things. Let's spot one gap.",
      cta: 'Walk through it',
      initialMessage: 'Help me audit how visible my best work is at my current job and pick one thing to fix this week.',
    }));
    pool.push(base({
      headline: 'Refresh your story for the next role.',
      followup: 'Even if you are not looking, the narrative needs upkeep.',
      cta: 'Sharpen with Dilly',
      initialMessage: 'Help me refresh my career story for the next role I would want, even if I am not actively looking.',
    }));
  } else if (mode === 'student') {
    if (userPath === 'dropout') {
      pool.push(base({
        headline: 'Ship one visible thing this week.',
        followup: 'Commit, post, demo. Receipts beat resumes.',
        cta: 'Plan the ship',
        initialMessage: "I'm a dropout working on proof-over-paper. Help me pick the one thing to ship this week.",
      }));
      pool.push(base({
        headline: 'Document one project on a public page.',
        followup: 'A live link is a credential a degree cannot match.',
        cta: 'Draft it',
        initialMessage: 'Help me write a short public project page for one thing I built - what to include and how to frame it.',
      }));
    } else if (userPath === 'international_grad') {
      pool.push(base({
        headline: 'Research one sponsor-friendly company this week.',
        followup: 'Save it to your target list, then tailor a fit read.',
        cta: 'Start research',
        initialMessage: "I'm on an international-grad path. Help me pick one sponsor-friendly company to research deeply this week.",
        destination: 'jobs',
      }));
      pool.push(base({
        headline: 'Map your visa timeline against your search.',
        followup: 'Dates first, applications second. Dilly can structure it.',
        cta: 'Map it',
        initialMessage: 'Help me build a visa-aware job search timeline for the next 6 months.',
      }));
    }
    pool.push(base({
      headline: 'Apply to 3 roles this week.',
      followup: 'Dilly will tailor a fit read on each.',
      cta: 'Open jobs',
      initialMessage: 'Help me pick 3 roles to apply to this week. Start with the strongest matches.',
      destination: 'jobs',
    }));
    pool.push(base({
      headline: 'Teach Dilly 3 more things about you this week.',
      followup: 'Every fact sharpens the guidance and the fit reads.',
      cta: 'Talk to Dilly',
      initialMessage: 'Help me add 3 more things about my experience that a recruiter would want to know.',
    }));
    pool.push(base({
      headline: `Push one conversation forward this week, ${firstName}.`,
      followup: 'A referral beats a cold app. Pick the person, draft the message.',
      cta: 'Start with Dilly',
      initialMessage: 'Help me draft one warm outreach message to someone in my target field this week.',
    }));
    pool.push(base({
      headline: 'Polish one resume bullet today.',
      followup: 'Numbers, verbs, outcomes. Dilly tightens it in five minutes.',
      cta: 'Tighten it',
      initialMessage: 'Help me rewrite ONE bullet on my resume to be sharper, more specific, and more measurable.',
    }));
    pool.push(base({
      headline: 'Pick one skill to learn this week.',
      followup: 'A 30-minute focused session beats two hours of scrolling jobs.',
      cta: 'Plan the session',
      initialMessage: 'Help me pick ONE skill to learn this week that maps to the roles I want.',
    }));
  } else {
    // mode === 'seeker'
    if (userPath === 'senior_reset') {
      pool.push(base({
        headline: 'Warm up one past colleague this week.',
        followup: 'People in your network hire first. Dilly will help you draft.',
        cta: 'Draft with Dilly',
        initialMessage: "I'm reopening my job search. Help me draft a check-in to one former colleague this week.",
      }));
      pool.push(base({
        headline: 'List 5 companies that respect your seniority.',
        followup: 'Skip the entry-level firehose. Aim where your level lands.',
        cta: 'Build the list',
        initialMessage: 'Help me build a target list of 5 companies that hire at my level and respect my experience.',
      }));
    }
    if (userPath === 'career_switch') {
      pool.push(base({
        headline: 'Publish one skill-transfer proof this week.',
        followup: 'A short project or case study signals the pivot is real.',
        cta: 'Plan it',
        initialMessage: "I'm switching careers. Help me pick ONE small project or case study I can publish this week.",
      }));
      pool.push(base({
        headline: 'Translate one past role into the new field.',
        followup: 'The same work, told in the new language. That is the pivot resume.',
        cta: 'Translate it',
        initialMessage: 'Help me rewrite one bullet from my previous career so it reads to recruiters in the field I am switching into.',
      }));
    }
    if (userPath === 'parent_returning') {
      pool.push(base({
        headline: 'Set one coffee chat this week.',
        followup: 'Returning to work starts with people, not postings.',
        cta: 'Find the person',
        initialMessage: "I'm returning to work after a career gap. Help me pick the one person to reach out to this week.",
      }));
      pool.push(base({
        headline: 'Frame your gap in one tight line.',
        followup: 'A clean answer makes the gap a non-issue. Dilly drafts it.',
        cta: 'Draft the line',
        initialMessage: 'Help me write one short, confident sentence to explain my career gap to recruiters.',
      }));
    }
    pool.push(base({
      headline: appCount < 5
        ? 'Apply to 5 strong matches this week.'
        : 'Book one conversation this week.',
      followup: appCount < 5
        ? 'Dilly will tailor a fit read on each one.'
        : 'A call beats three cold applications.',
      cta: appCount < 5 ? 'Open jobs' : 'Start with Dilly',
      initialMessage: appCount < 5
        ? 'Help me pick 5 strong roles to apply to this week.'
        : "I've been applying consistently. Help me shift toward conversations this week.",
      destination: appCount < 5 ? 'jobs' : 'chat',
    }));
    pool.push(base({
      headline: 'Tighten your story for one role.',
      followup: 'A targeted narrative reads sharper than a one-size resume.',
      cta: 'Sharpen it',
      initialMessage: 'Help me tailor my story for ONE specific role I am chasing this week.',
    }));
    pool.push(base({
      headline: 'Re-engage one warm contact today.',
      followup: 'A 90-second message often beats a 90-minute application.',
      cta: 'Draft it',
      initialMessage: 'Help me write a short re-engagement message to one person in my network I have lost touch with.',
    }));
  }

  // Pinned items always go first so urgency wins; rotation cycles
  // only the non-urgent pool. If everything is empty (shouldn't
  // happen), return a single fallback so the card never crashes.
  const all = [...pinned, ...pool];
  if (all.length === 0) {
    all.push(base({
      headline: 'Pick one career move this week.',
      followup: 'Dilly will help you make it specific.',
      cta: 'Talk to Dilly',
      initialMessage: 'Help me pick ONE concrete career move to make this week.',
    }));
  }
  return all;
}

function generatePlan(i: PlanInputs, variantIdx: number = 0): YourPlan {
  const variants = generatePlanVariants(i);
  const safe = variants.length > 0 ? variants : [{
    mode: i.mode,
    pathKey: i.userPath,
    headline: 'Pick one career move this week.',
    followup: 'Dilly will help you make it specific.',
    cta: 'Talk to Dilly',
    initialMessage: 'Help me pick ONE concrete career move to make this week.',
    destination: 'chat' as const,
    generatedAt: today(),
  }];
  return safe[variantIdx % safe.length];
}

/**
 * Bump the variant index. Called when the user taps the plan CTA -
 * by the time they navigate back to home, the next variant will be
 * showing. We keep the date so a tap at 11:59 PM rolls over cleanly.
 */
export async function markPlanActionTaken(): Promise<void> {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY);
    const stored = raw ? JSON.parse(raw) : {};
    const idx = typeof stored.variantIdx === 'number' ? stored.variantIdx : 0;
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify({
      ...stored,
      date: stored.date || today(),
      variantIdx: idx + 1,
    }));
  } catch {}
}

interface StoredPlanState {
  date: string;
  variantIdx: number;
  mode?: string;
  userPath?: string;
}

async function readStoredState(): Promise<StoredPlanState> {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY);
    if (!raw) return { date: today(), variantIdx: 0 };
    const parsed = JSON.parse(raw);
    return {
      date: typeof parsed.date === 'string' ? parsed.date : today(),
      variantIdx: typeof parsed.variantIdx === 'number' ? parsed.variantIdx : 0,
      mode: parsed.mode,
      userPath: parsed.userPath,
    };
  } catch {
    return { date: today(), variantIdx: 0 };
  }
}

async function writeStoredState(s: StoredPlanState): Promise<void> {
  try {
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(s));
  } catch {}
}

/**
 * Hook: returns today's plan, cycling to a new variant each time the
 * user taps the CTA and returns to the screen. Re-reads storage on
 * focus so the increment from markPlanActionTaken (fired in the card)
 * shows up the moment home becomes visible again.
 */
export function useYourPlan(inputs: PlanInputs | null): YourPlan | null {
  const [plan, setPlan] = useState<YourPlan | null>(null);

  // Recompute the plan from the current inputs + variantIdx in storage.
  // Resets idx to 0 when mode/path changes (different user state) or
  // when the date rolls over (fresh day starts at variant 0).
  const recompute = useCallback(async () => {
    if (!inputs) {
      setPlan(null);
      return;
    }
    const stored = await readStoredState();
    const dayChanged = stored.date !== today();
    const contextChanged = stored.mode !== inputs.mode || stored.userPath !== inputs.userPath;
    const variantIdx = (dayChanged || contextChanged) ? 0 : stored.variantIdx;

    if (dayChanged || contextChanged) {
      await writeStoredState({
        date: today(),
        variantIdx: 0,
        mode: inputs.mode,
        userPath: inputs.userPath,
      });
    }
    setPlan(generatePlan(inputs, variantIdx));
  }, [
    inputs?.mode,
    inputs?.userPath,
    inputs?.appCount,
    inputs?.factCount,
    inputs?.interviewingCount,
    inputs?.currentRole,
    inputs?.recentDeadline?.label,
    inputs?.recentDeadline?.daysUntil,
  ]);

  // Initial + input-driven recompute.
  useEffect(() => { recompute(); }, [recompute]);

  // Re-read storage every time the host screen regains focus - picks
  // up the variantIdx bump from markPlanActionTaken without needing
  // any cross-component state plumbing.
  useFocusEffect(useCallback(() => { recompute(); }, [recompute]));

  return plan;
}

export default useYourPlan;
