/**
 * Major US cities for job location autocomplete.
 * Format: "City, ST" for display and backend matching.
 */
export const JOB_CITIES: string[] = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "Charlotte, NC",
  "San Francisco, CA",
  "Indianapolis, IN",
  "Seattle, WA",
  "Denver, CO",
  "Boston, MA",
  "Nashville, TN",
  "Detroit, MI",
  "Portland, OR",
  "Las Vegas, NV",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Mesa, AZ",
  "Sacramento, CA",
  "Atlanta, GA",
  "Kansas City, MO",
  "Colorado Springs, CO",
  "Raleigh, NC",
  "Miami, FL",
  "Omaha, NE",
  "Long Beach, CA",
  "Virginia Beach, VA",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Tampa, FL",
  "Arlington, TX",
  "New Orleans, LA",
  "Wichita, KS",
  "Cleveland, OH",
  "Bakersfield, CA",
  "Aurora, CO",
  "Honolulu, HI",
  "Anaheim, CA",
  "Santa Ana, CA",
  "St. Louis, MO",
  "Riverside, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "Pittsburgh, PA",
  "Anchorage, AK",
  "Stockton, CA",
  "Cincinnati, OH",
  "St. Paul, MN",
  "Toledo, OH",
  "Newark, NJ",
  "Greensboro, NC",
  "Plano, TX",
  "Lincoln, NE",
  "Orlando, FL",
  "Irvine, CA",
  "Newark, DE",
  "Durham, NC",
  "Chula Vista, CA",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "St. Petersburg, FL",
  "Laredo, TX",
  "Madison, WI",
  "Chandler, AZ",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Buffalo, NY",
  "Gilbert, AZ",
  "Glendale, AZ",
  "North Las Vegas, NV",
  "Winston-Salem, NC",
  "Chesapeake, VA",
  "Norfolk, VA",
  "Fremont, CA",
  "Boise, ID",
  "Richmond, VA",
  "Baton Rouge, LA",
  "San Bernardino, CA",
  "Birmingham, AL",
  "Spokane, WA",
  "Rochester, NY",
  "Des Moines, IA",
  "Modesto, CA",
  "Fayetteville, NC",
  "Tacoma, WA",
  "Fontana, CA",
  "Oxnard, CA",
  "Moreno Valley, CA",
  "Frisco, TX",
  "Rochester, MN",
  "Yonkers, NY",
  "Salt Lake City, UT",
  "Grand Rapids, MI",
  "Huntsville, AL",
  "Grand Prairie, TX",
  "Knoxville, TN",
  "Worcester, MA",
  "Newport News, VA",
  "Brownsville, TX",
  "Santa Clarita, CA",
  "Overland Park, KS",
  "Providence, RI",
  "Garden Grove, CA",
  "Santa Rosa, CA",
  "Chattanooga, TN",
  "Oceanside, CA",
  "Fort Lauderdale, FL",
  "Rancho Cucamonga, CA",
  "Santa Maria, CA",
  "Port St. Lucie, FL",
  "Tempe, AZ",
  "Ontario, CA",
  "Vancouver, WA",
  "Springfield, MO",
  "Cape Coral, FL",
  "Pembroke Pines, FL",
  "Sioux Falls, SD",
  "Peoria, AZ",
  "Lancaster, CA",
  "Elk Grove, CA",
  "Palmdale, CA",
  "Springfield, MA",
  "Salinas, CA",
  "Pomona, CA",
  "Pasadena, TX",
  "Jackson, MS",
  "Paterson, NJ",
  "Kansas City, KS",
  "Torrance, CA",
  "Savannah, GA",
  "Escondido, CA",
  "Mesquite, TX",
  "Sunnyvale, CA",
  "Hollywood, FL",
  "Pasadena, CA",
  "Orange, CA",
  "Dayton, OH",
  "Cary, NC",
  "Hampton, VA",
  "Warren, MI",
  "Miramar, FL",
  "Rockford, IL",
  "Charleston, SC",
  "Columbia, SC",
  "Olathe, KS",
  "Sterling Heights, MI",
  "New Haven, CT",
  "Waco, TX",
  "Thousand Oaks, CA",
  "Cedar Rapids, IA",
  "Elizabeth, NJ",
  "Visalia, CA",
  "Gainesville, FL",
  "Thornton, CO",
  "Roseville, CA",
  "Carrollton, TX",
  "Coral Springs, FL",
  "Stamford, CT",
  "Simi Valley, CA",
  "Concord, CA",
  "Hartford, CT",
  "Kent, WA",
  "Lafayette, LA",
  "Midland, TX",
  "Surprise, AZ",
  "Denton, TX",
  "Victorville, CA",
  "Evansville, IN",
  "Santa Clara, CA",
  "Abilene, TX",
  "Athens, GA",
  "Vallejo, CA",
  "Allentown, PA",
  "Norman, OK",
  "Beaumont, TX",
  "Independence, MO",
  "Murfreesboro, TN",
  "Ann Arbor, MI",
  "Springfield, IL",
  "Berkeley, CA",
  "Peoria, IL",
  "Provo, UT",
  "El Monte, CA",
  "Columbia, MO",
  "Lansing, MI",
  "Fargo, ND",
  "Downey, CA",
  "Costa Mesa, CA",
  "Wilmington, NC",
  "Arvada, CO",
  "Inglewood, CA",
  "Miami Gardens, FL",
  "Carlsbad, CA",
  "Westminster, CO",
  "Rochester, MN",
  "Odessa, TX",
  "Manchester, NH",
  "Elgin, IL",
  "West Jordan, UT",
  "Round Rock, TX",
  "Clearwater, FL",
  "Waterbury, CT",
  "Gresham, OR",
  "Fairfield, CA",
  "Billings, MT",
  "Lowell, MA",
  "San Buenaventura, CA",
  "Pueblo, CO",
  "High Point, NC",
  "West Covina, CA",
  "Richmond, CA",
  "Murrieta, CA",
  "Cambridge, MA",
  "Antioch, CA",
  "Temecula, CA",
  "Norwalk, CA",
  "Centennial, CO",
  "Everett, WA",
  "Palm Bay, FL",
  "Wichita Falls, TX",
  "Green Bay, WI",
  "Daly City, CA",
  "Burbank, CA",
  "Richardson, TX",
  "Pompano Beach, FL",
  "North Charleston, SC",
  "Broken Arrow, OK",
  "Boulder, CO",
  "West Palm Beach, FL",
  "Santa Maria, CA",
  "El Cajon, CA",
  "Davenport, IA",
  "Rialto, CA",
  "Las Cruces, NM",
  "San Mateo, CA",
  "Lewisville, TX",
  "South Bend, IN",
  "Lakeland, FL",
  "Erie, PA",
  "Tyler, TX",
  "Pearland, TX",
  "College Station, TX",
  "Kenosha, WI",
  "Sandy Springs, GA",
  "Clovis, CA",
  "League City, TX",
  "Davie, FL",
  "Denton, TX",
  "San Angelo, TX",
  "Allen, TX",
  "Rio Rancho, NM",
  "Las Vegas, NM",
  "Sparks, NV",
  "Vacaville, CA",
  "Edinburg, TX",
  "Lee's Summit, MO",
  "South San Francisco, CA",
  "Waukegan, IL",
  "San Marcos, TX",
  "Longmont, CO",
  "Boca Raton, FL",
  "Port Arthur, TX",
  "Carson, CA",
  "Lake Forest, CA",
  "Compton, CA",
  "Quincy, MA",
  "Mission Viejo, CA",
  "Yuma, AZ",
  "Henderson, NV",
  "Miramar, FL",
  "Bryan, TX",
  "Chico, CA",
  "New Braunfels, TX",
  "Roanoke, VA",
  "Albany, NY",
  "Jurupa Valley, CA",
  "Indio, CA",
  "Spokane Valley, WA",
  "Georgetown, TX",
  "Gilbert, AZ",
  "Lake Charles, LA",
  "Orem, UT",
  "Bellingham, WA",
  "Richmond, KY",
  "St. George, UT",
  "San Leandro, CA",
  "Nampa, ID",
  "Bloomington, IN",
  "Deltona, FL",
  "Hawthorne, CA",
  "Duluth, MN",
  "Carmel, IN",
  "Suffolk, VA",
  "Clinton, MI",
  "Deerfield Beach, FL",
  "Newton, MA",
  "Trenton, NJ",
  "Citrus Heights, CA",
  "State College, PA",
  "Newport Beach, CA",
  "Bend, OR",
  "Fishers, IN",
  "Danbury, CT",
  "San Marcos, CA",
  "Hillsboro, OR",
  "Meridian, ID",
  "Lawton, OK",
  "North Port, FL",
  "Rapid City, SD",
  "Eau Claire, WI",
  "Rio Rancho, NM",
  "Edmond, OK",
  "Redding, CA",
  "Schaumburg, IL",
  "Livermore, CA",
  "Menifee, CA",
  "San Ramon, CA",
  "Bethlehem, PA",
  "Wyoming, MI",
  "Owensboro, KY",
  "Sandy, UT",
  "Cicero, IL",
  "Alhambra, CA",
  "Hoover, AL",
  "Lakeville, MN",
  "Apple Valley, MN",
  "Greece, NY",
  "Nashua, NH",
  "Mount Vernon, NY",
  "Rock Hill, SC",
  "Jersey City, NJ",
  "Lorain, OH",
  "Novato, CA",
  "Lacey, WA",
  "Iowa City, IA",
  "Muskegon, MI",
  "Turlock, CA",
  "Temple, TX",
  "La Habra, CA",
  "Middletown, OH",
  "Baldwin Park, CA",
  "Chino Hills, CA",
  "Mentor, OH",
  "Chino, CA",
  "Brentwood, CA",
  "New Bedford, MA",
  "South Jordan, UT",
  "San Luis Obispo, CA",
  "Morgan Hill, CA",
  "Bozeman, MT",
  "Fort Collins, CO",
  "Flagstaff, AZ",
  "Greenville, NC",
  "Davis, CA",
  "Bismarck, ND",
  "Rogers, AR",
  "St. Augustine, FL",
  "Roy, UT",
  "Winter Haven, FL",
  "Fayetteville, AR",
  "Lynchburg, VA",
  "Palo Alto, CA",
  "Mountain View, CA",
  "Sunnyvale, CA",
  "Berkeley, CA",
  "Redwood City, CA",
  "Menlo Park, CA",
  "Cupertino, CA",
];

/** Deduplicated city list for autocomplete */
export const JOB_CITIES_LIST = [...new Set(JOB_CITIES)];
